version: "3"
services:
  # Commented out for 'npm run dev' work
  #nextjs:
  #  build: ./
  #  image: wforbes87/wf-nextjs-practice
  #  environment:
  #    - PORT=3000
  #  ports:
  #    - "3000:3000"
  #  depends_on:
  #    - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wforbes
      - MONGO_INITDB_ROOT_PASSWORD=thepassword
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis
volumes:
  mongo-db: